### PR TITLE
Move authorization logic to a dedicated ResourcePolicy

### PR DESCRIPTION
**Pull request by MtDalPizzol**
This PR moves the authorization logic to a dedicated `ResourcePolicy`.

This will give devs the ability to customize authorization logic when needed.

Currently, if you need to customize how an action is authorized, you'll have to use the Service Container to rebind every class inside `src/Http/Request` plus every other class that makes checks using `->hasPermission()`.

Having a dedicated `ResourcePolicy` is also more aligned with Statamic, since the process to customize authorization will be exactly the same described in Statamic's docs to customize the `EntryPolicy`.

For instance:

```php
<?php
// app/Policies/ResourcePolicy.php

namespace App\Policies;

use DoubleThreeDigital\Runway\Policies\ResourcePolicy as RunwayResourcePolicy;
use Illuminate\Auth\Access\HandlesAuthorization;

class ResourcePolicy extends RunwayResourcePolicy
{
    use HandlesAuthorization;

    public function edit($user, $resource)
    {
       // Do custom checks here before running the default ones

        return parent::edit($user, $resource);
    }
}

```

```php
// app/Providers/AppServiceProvider.php

public function boot()
{
    $this->app->bind(RunwayResourcePolicy::class, ResourcePolicy::class);
}
```

### CODE REVIEW

**Comment by duncanmcclean** [comment]
Something weird is going on with your fork... all of the commits from your previous PR are showing up as separate changes on this PR which makes it difficult to review.

I don't suppose you'd be able to recreate your fork and re-open this PR?

1. Obviously make a copy of any file changes you've made to your fork.
2. Delete your fork on GitHub and locally
3. Fork the Runway repository again & clone it down
4. Then, for any new PRs you open, create a new branch for the PR (don't create PRs from your `main` branch, I think that may be what's causing issues here)
    * If the `main` branch on your fork becomes out-of-date, GitHub has a ['Sync fork' button](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) to sync your fork with the main repository.

I hope that makes sense?

**Comment by duncanmcclean** [comment]
I've had a quick look, PR looks great, we should have been using policies since the start! 

I'll give this a proper review once the fork issue has been resolved.

**Comment by MtDalPizzol** [comment]
> 4. Then, for any new PRs you open, create a new branch for the PR (don't create PRs from your `main` branch, I think that may be what's causing issues here)
>    
>    * If the `main` branch on your fork becomes out-of-date, GitHub has a ['Sync fork' button](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) to sync your fork with the main repository.

Yeah...Sorry for that. Surely this was the problem. I notice that and I wasn't sure if this was normal. I probably did something wrong. I have never contributed to any repo before. So, I don't exactly know what is "right" here. But no worries. I'll try to redo the work on a separate branch. If that doesn't work, I'll fork it again from scratch...

**Comment by duncanmcclean** [comment]
> > 4. Then, for any new PRs you open, create a new branch for the PR (don't create PRs from your `main` branch, I think that may be what's causing issues here)
> >    
> >    * If the `main` branch on your fork becomes out-of-date, GitHub has a ['Sync fork' button](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) to sync your fork with the main repository.
> 
> Yeah...Sorry for that. Surely this was the problem. I notice that and I wasn't sure if this was normal. I probably did something wrong. I have never contributed to any repo before. So, I don't exactly know what is "right" here. But no worries. I'll try to redo the work on a separate branch. If that doesn't work, I'll fork it again from scratch...

Thanks! 👍

**Pull request closed without merging**
